management:
  endpoints:
    web:
      exposure:
        include: "*"

cloud:
  aws:
    # Set by autoconfigure
    # credentials:
    #   accessKey: ${AWS_ACCESS_KEY_ID}
    #   secretKey: ${AWS_SECRET_ACCESS_KEY}
    stack:
      # CloudFormationのスタック名を自動取得しない
      auto: false
    region:
      # リージョン名を自動取得しない
      auto: false
      # リージョン名（例. ap-northeast-1）
      # static: ${AWS_REGION}
      static: ap-northeast-1
