management:
  endpoints:
    web:
      exposure:
        include: "*"

cloud:
  aws:
    # Set by autoconfigure
    # credentials:
    #   accessKey: ${AWS_ACCESS_KEY_ID}
    #   secretKey: ${AWS_SECRET_ACCESS_KEY}
    stack:
      # CloudFormationのスタック名を自動取得しない
      auto: false
    region:
      # リージョン名を自動取得しない
      auto: false
      # リージョン名（例. ap-northeast-1）
      # static: ${AWS_REGION}
      static: ap-northeast-1

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

  # Does not work?
  flyway:
    enabled: true
    baseline-version: 1.0.0
    baseline-on-migrate: true
    url: jdbc:mysql://h-cent-doc01.designet.local:3306/spotleft?character_set_server=utf8mb4
    user: spring
    password: boot
    locations: filesystem:src/main/resources/db/migration

cron:
  cron1: "${SPOTLEFT_CRON:0 55 8 * * MON-FRI}"

logging:
  level:
    com.daichi703n: ${LOG_LEVEL:INFO}
  # file: logs/application.log
  exception-conversion-word: "\t%replace(%replace(%xEx){'\n','\\\\n'}){'\t','    '}%nopex"
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSSZ}){faint} %clr(${logging.pattern.level:-%5p}) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger){cyan} %clr(:){faint} %replace(%m){'\n','\\\\n'}${logging.exception-conversion-word:%wEx}%n"
